[package]
name = "ojcmp"
version = "0.2.3-dev"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
license = "MIT"
description = "online judge comparer"
repository = "https://github.com/ThinkSpiritLab/ojcmp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.69"
structopt = "0.3.14"
backtrace = "0.3.46"
lexical-core = "0.7.4"
thiserror = "1.0.18"

[dev-dependencies]
rand = "0.7.3"
criterion = "0.3.2"

[[bench]]
name = "n_random"
harness = false
